### ISSUE TITLE
Suggestion for a new option: do not show the applications with a single visible window

### ISSUE THREAD

**Issue by mateiacd** [adamecr/AppSwitcherBar#1]
I would like to have the  option of showing only the applications that create two or more visible windows

**Comment by adamecr** [comment]
Hi @mateiacd, thanks for the suggestion, I think this might be a part of the next release. Have some idea, need a bit of testing

**Comment by adamecr** [comment]
Released in [version 1.2.0](https://github.com/adamecr/AppSwitcherBar/releases/tag/v1.2.0)
The option is disabled by default, set `HideSingleWindowApps` in `appsettings.json` to `true`

**Comment by adamecr** [comment]
closing the ticket
