### ISSUE TITLE
Feature Request - Display on All Monitors

### ISSUE THREAD

**Issue by relipse** [adamecr/AppSwitcherBar#10]
It would be nice to have it display on all monitors.

**Comment by relipse** [comment]
A work around is this: Copy the AppSwitcherBar application folder to another location and run the executable in both directories. 
Then you will have 2 appswitcherbars and you can move one to another monitor.
Thanks!

**Comment by adamecr** [comment]
I'm afraid that this would need quite a redesign of the application (model, view and controls) to have a multiple presentation (views) of the same data.
Will keep it in mind in case there will be some major redesign in future. As of now, I think that the work around you proposed is the best way how to do the multi-monitor display.
