### ISSUE TITLE
JumpList items order

### ISSUE THREAD

**Issue by Capital-Z** [adamecr/AppSwitcherBar#2]
I like your project, I was looking for something like this to let me use vertical taskbar since window 11 came out. I was actually thinking of writing my own and then I found your project. Thank you for it.
One problem is the JumpLists are not the same as what the standard taskbar is showing. I looked into it and did some coding to make it work. Mainly it is using the "DestList" stream in the automatic destinations in order to properly sort them and move some to "Pinned" category. It is now showing the same as Win 11 taskbar JumpLists.
Would you like me to contribute the modifications here or you rather keep it separate?

**Comment by adamecr** [comment]
Hello @Capital-Z , thanks for the feedback, I appreciate it.
You're right, there is a discreapancy between the Win and app JumpLists. I was fighting quite a bit with parsing the DestList stream, so the decision was to skip it for the moment and try to find the other way.
Recently I found [Open-Shell](https://github.com/Open-Shell/Open-Shell-Menu) project that gave me some hints. I'm updating the JumpListService and the prototype seems promising, just need to "productionize" the code and update the documentation.
I'd like to prepare the release of version 1.3 that will add the search windows/apps functionality and also the updated JumpLists.
The plan is to do the release before end of October - still two weekends ahead ;-). 
Would it be ok for you to wait for the updated version and then we will see whether the solution will be good or we move forward with yours?
Thanks
Radek

**Comment by Capital-Z** [comment]
Hello Radek,
No problem. I'll wait and try 1.3 when it comes out. Check https://github.com/EricZimmerman/JumpList, quite useful.
RegardsZhivko
Sent from Yahoo Mail on Android 
 
  On Wed, 19 Oct 2022 at 12:04 pm, Radek ***@***.***> wrote:   


Hello @Capital-Z , thanks for the feedback, I appreciate it.
You're right, there is a discreapancy between the Win and app JumpLists. I was fighting quite a bit with parsing the DestList stream, so the decision was to skip it for the moment and try to find the other way.
Recently I found Open-Shell project that gave me some hints. I'm updating the JumpListService and the prototype seems promising, just need to "productionize" the code and update the documentation.
I'd like to prepare the release of version 1.3 that will add the search windows/apps functionality and also the updated JumpLists.
The plan is to do the release before end of October - still two weekends ahead ;-).
Would it be ok for you to wait for the updated version and then we will see whether the solution will be good or we move forward with yours?
Thanks
Radek

**Comment by adamecr** [comment]
Hello Zhivko,
Release 1.3 is [published](https://github.com/adamecr/AppSwitcherBar/releases/tag/v1.3.0), so you can have a look whether the updated jump list functionality cover your needs.

BTW: I know Eric's work and he really did a good job. I have a bit different approach - trying to find and utilize the win API as much as possible. But true, it's always good to check as much sources as possible...

cc @Capital-Z

**Comment by Capital-Z** [comment]
Hello Radek
Jump lists now work great. Thank you for the update.The other thing I did before was too adjust the colours. I use dark windows theme and it does not match the static colours you have.I can put that as a feature request for customisable/configurable colours if you want.
Cheers Zhivko

 
 
  On Mon, 24 Oct 2022 at 8:14 am, Radek ***@***.***> wrote:   


Hello Zhivko,
Release 1.3 is published, so you can have a look whether the updated jump list functionality cover your needs.

BTW: I know Eric's work and he really did a good job. I have a bit different approach - trying to find and utilize the win API as much as possible. But true, it's always good to check as much sources as possible...

cc @Capital-Z

**Comment by adamecr** [comment]
Hello Zhivko,
I created a [[Feature Request] Customisable/configurable colours](https://github.com/adamecr/AppSwitcherBar/issues/4) and added some comment in there. 
I'll close this issue for jumplists

cc @Capital-Z
