### ISSUE TITLE
Thumbnail popup in vertical mode

### ISSUE THREAD

**Issue by Capital-Z** [adamecr/AppSwitcherBar#3]
In vertical mode the thumbnail popup is covering other buttons. Since it is shown instantly it prevents from clicking on a desired app when the app button is under the pop-up.
It would be good to have some timeout, e.g. 1/3 of second, before the pop-up like the standard OS taskbar behaviour.
Also in vertical mode the thumbnail should be positioned on the right/left of the app button, not under/above. This can be done by dynamically changing the "Placement" property of the ThumbnailPopup.

**Comment by adamecr** [comment]
Hello Zhivko,
I didn't think about the popup placement in this case, as I don't "really" use the vertical mode. So it's a good catch, thanks. The fix should be simple and quick

It's also a good proposal with the delayed display of thumbnail. I have some idea how to do it, will give it a try and let's see.

I think i can patch it over the weekend

**Comment by adamecr** [comment]
Both updates seems to be working, I'll use it for some time to test it and if there will be no hiccups, I'll relase the patch at the end of week

cc @Capital-Z

**Comment by adamecr** [comment]
Released in [Version 1.3.1](https://github.com/adamecr/AppSwitcherBar/releases/tag/v1.3.1)

cc @Capital-Z

**Comment by Capital-Z** [comment]
Both work fine for me now. Thank you
