### ISSUE TITLE
[Feature Request] Customisable/configurable colours

### ISSUE THREAD

**Issue by adamecr** [adamecr/AppSwitcherBar#4]
[@Capital-Z](https://github.com/Capital-Z): The other thing I did before was too adjust the colours. I use dark windows theme and it does not match the static colours you have.I can put that as a feature request for customisable/configurable colours

**Comment by adamecr** [comment]
Hello Zhivko,
thanks for the suggesion - actually it's on my backlog and I'm still thinking how to approach it as WPF doesn't easily support the Windows themes and theming is a bit heavy weight. Frankly I don't want to use the 3rd party libraries like WPF UI because I'm playing with the windows quite low level and want to have as much control as possible.

Will play a bit with the ideas and will try to do it together with localization support (that's the other task from my backlog)

**Comment by adamecr** [comment]
I was able to adopt WPF UI to support themes. Doing so, I had to do major redesigh of the whole UI to better match the modernized look.
It will be a part of verision 2.0.0 also with some additional functionality like support for localization (UI translations) or Start menu like application list. It's now in testing and documentation phase, but sharing a teaser

![themes teaser](https://user-images.githubusercontent.com/37288047/201555257-c9065b26-30d6-44b9-8d40-be6afc11df23.png)

**Comment by Capital-Z** [comment]
This looks great. Can't wait to try it.

**Comment by adamecr** [comment]
I finished some fixes I want to add to release as well as the documentation for version 2.
I'll use it on my "daily work" during the next week to do a bit more testing and then will do the merge end release

**Comment by adamecr** [comment]
Version 2.0.0 with light/dark theme released

**Comment by Capital-Z** [comment]
Tried it today, looks way better in black, Much obliged.

**Comment by adamecr** [comment]
closing the issue
