### ISSUE TITLE
Settings reset on start in version 2.0

### ISSUE THREAD

**Issue by Capital-Z** [adamecr/AppSwitcherBar#5]
For example switching off "Auto size" properly updates "appsettings.user.json", but the default value is restored on re-start even when both settings files have "AppBarAutoSize": false. Same with other settings like "AppBarDock".

**Comment by adamecr** [comment]
Confirming the bug - the root cause it that the static design time settings are being initialized even in run-time and overrides the user settings. Will release the patch in a few

**Comment by adamecr** [comment]
@Capital-Z , thanks for reporting the bug. I made a quick fix as the bug has quite an impact, hope I didn't break anything else by the fix. Released the fix as patch 2.0.1.,

**Comment by Capital-Z** [comment]
Fixed indeed. That was quick
