### ISSUE TITLE
UI not responsive when some app does not respond to SendMessage

### ISSUE THREAD

**Issue by Capital-Z** [adamecr/AppSwitcherBar#6]
For example SendMessage line in the code:
WndAndApp.GetWindowIcon()
{
...
...SendMessageA(hwnd, WM_GETICON
...
}
freezes the bar when the app corresponding to the hwnd is being debugged.
Not very "programmer friendly" :).

Note: There are probably many ways to work around this, e.g. SendMessageTimeout() Windows API comes to mind.

**Comment by adamecr** [comment]
Added timeout for WM_GETICON request. The fix will be a part of the next release

**Comment by adamecr** [comment]
Fix released with [Version 2.1.0](https://github.com/adamecr/AppSwitcherBar/releases/tag/v2.1.0)
