### ISSUE TITLE
Feature Request - Turn off Italicized items and use it like the old regular task bar

### ISSUE THREAD

**Issue by relipse** [adamecr/AppSwitcherBar#9]
Love the AppSwitcherBar! Excellent for Windows 11!
It would be nice to be able to turn off all of the italicized items and just use it like the old task bar used to be.

**Comment by adamecr** [comment]
Hello @relipse , I'm happy to hear thar you like the app.

Just want to clarify the term "italicized items". Do you mean the application buttons in italic not representing the open app/window but the applications pinned to the Win task bar?

If so, changing the `ShowPinnedApps` item in `appsettings.json` to `false` should be the functionality, you're looking for.
Hope this help

**Comment by relipse** [comment]
Yes that helped! Thank you.
